### ISSUE TITLE
Compiled with some warnings , but not connecting to TG

### ISSUE THREAD

**Issue by Disorden456** [1N73LL1G3NC3x/Nightmangle#1]
![image](https://github.com/1N73LL1G3NC3x/Nightmangle/assets/86217941/3a42e1c8-8fb4-46c0-9f85-f28440e35cc8)
![image](https://github.com/1N73LL1G3NC3x/Nightmangle/assets/86217941/eb986106-ff82-41bc-a791-ca5155682406)

![image](https://github.com/1N73LL1G3NC3x/Nightmangle/assets/86217941/3ffb8726-9b78-45ba-9b3a-e0ac7339493c)

**Comment by 1N73LL1G3NC3x** [comment]
Nightmangle, when connected, does not send anything without the operator's command. The "/help" command should return a list of possible commands if the agent is running.

Also check that the antivirus has not killed the process, that it is running, for example with Task Manager.

**Comment by 1N73LL1G3NC3x** [comment]
I checked the agent's work through various VPN, from some locations access to TG may be blocked.

**Comment by Disorden456** [comment]
Great  , it works now , i had to give the /help command  , thankyou , it is recomended to add a notification or a message saying  connection establised so thats its easier , or else we need to keep checking by the /help command always .  And also if you leave me youre contact ill provide the code to a better Stealer for browsers written in rust itself

**Comment by Disorden456** [comment]
also add an autostart feature

**Comment by 1N73LL1G3NC3x** [comment]
@el3ktraz 
You can tweet me @AlexMon360005. I'm thinking about adding more features and EDR evasion in next release, but it will be possible when I will have some free time.

**Comment by Disorden456** [comment]
great
